# Generated by Django 3.0.2 on 2020-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('standard', models.FloatField()),
                ('standard_hc', models.FloatField()),
                ('current', models.FloatField()),
                ('current_hc', models.FloatField()),
            ],
        ),
    ]
