# Generated by Django 3.0.2 on 2020-01-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
