# Generated by Django 3.0.2 on 2020-01-20 12:37

from django.db import migrations
from api import dp


def collect_data(apps, schema_editor):
    Item = apps.get_model('api', 'Item')
    # db_alias = schema_editor.connection.alias
    items = dp.collected_items
    for item in items:
        new_item = Item.objects.get_or_create(
            item_number=item['item_number'],
            name=item['name'],
            category=item['category'],
            type=item['type'],
            group=item['group'],
            standard=item[dp.standard],
            standard_hc=item[dp.standard_hc],
            current=item[dp.curr_league],
            current_hc=item[dp.curr_league_hc]
        )


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(collect_data, migrations.RunPython.noop),
    ]
